$(document).ready(function(){
    $('.slick_role').slick({
        arrows:false,
        dots:true,
        adaptiveHeight:true,
        speed:1000,
        easing:'ease',
    });
});

$(document).ready(function(){
    $('.slider_row').slick({
        arrows:true,
        dots:false,
        slidesToShow:5,
        adaptiveHeight:true,
        speed:1000,
        easing:'ease'
    });
});